export const IS_LAVA_SET_AS_DEFAULT_NETWORK = 'IS_LAVA_SET_AS_DEFAULT_NETWORK';
export const IS_LAVA_SET_AS_DEFAULT_NETWORK_2 = 'IS_LAVA_SET_AS_DEFAULT_NETWORK_2';
export const IS_MATIC_SET_AS_DEFAULT_NETWORK = 'IS_MATIC_SET_AS_DEFAULT_NETWORK';
export const NETWORK_CONFIGUER_ID = 'NETWORK_CONFIGUER_ID';
